name: build

on: push

jobs:
  sphinx:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build HTML
        uses: XanaduAI/sphinx-action@08cb9868314fb5be5f28644b540a38b8faaf8e87
        with:
          pre-build-command: pip install myst-parser sphinx-rtd-theme
          docs-folder: .
      - name: Install RSA key
        run: |
          mkdir .ssh
          chmod 700 .ssh
          echo "${{ secrets.RSA_KEY }}" > .ssh/id_rsa
          chmod 600 .ssh/id_rsa
          echo "club1.fr ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBBC64tjZ1WjxMMoGeWiipApfCAaQe1sP/YFoNWYtckXV7XfFFKsBf70SHUw/oPjVZ1sdwcIL8wsH8Q00oYMIv7M=" > .ssh/known_hosts
      - name: Publish
        run: make publish USER=docs
